# YAML config for dataset, training, and model parameters

# Dataset parameters
dataset:
  n_flows_list: [2000]
  # n_links_max: 96
  # n_links_max: 768
  n_links_max: 16896
  n_hosts_list: [32]
  shard: 0
  shard_list: [0,4000,4000] # [start, end, num]
  sample_list: [0,1,1] # [start, end, num]
  lr: 10
  train_frac: 0.9
  topo_type: "_topology_flows"
  enable_segmentation: True
  segments_per_seq: 1
  sampling_method: "balanced" # weighted, uniform, balanced
  enable_abstime: False
  enable_topo: True
  flow_size_threshold: 100000000
  enable_flowsim_gt: False
  enable_flowsim_diff: True
  enable_remainsize: True
  enable_queuelen: True
  # current_period_len_idx: 0

# Model parameters
model:
  model_name: "lstm"
  input_size: 2
  n_layer: 2
  gcn_n_layer: 3
  loss_fn_type: "l1"
  hidden_size: 200
  gcn_hidden_size: 300
  dropout: 0.0
  enable_bidirectional: True
  enable_positional_encoding: False
  enable_gnn: True
  enable_lstm: True
  enable_lstm_in_gnn: False
  enable_link_state: True

# Training parameters
training:
  gpu: [3]
  n_epochs: 5
  batch_size: 1
  learning_rate: 0.0001
  num_workers: 2
  enable_val: False
  enable_dist: False