# YAML config for dataset, training, and model parameters

# Dataset parameters
dataset:
  n_flows_list: [2000]
  n_hosts_list: [5]
  shard: 0
  shard_list: [0,2000,200] # [start, end, num]
  sample_list: [0,1,1] # [start, end, num]
  lr: 10
  train_frac: 0.9
  topo_type: "_topo-pl-x_"
  output_type: "fctSldn" # fctSldn, queueLen
  enable_segmentation: True
  segments_per_seq: 10
  sampling_method: "balanced" # weighted, uniform, balanced
  enable_path: True
  flow_size_threshold: 100000000

# Model parameters
model:
  model_name: "lstm"
  input_size: 5
  n_layer: 2
  gcn_n_layer: 2
  loss_fn_type: "l1"
  hidden_size: 256
  gcn_hidden_size: 16
  dropout: 0.0
  enable_bidirectional: True
  enable_positional_encoding: False
  enable_gnn: True

# Training parameters
training:
  gpu: [1]
  n_epochs: 5
  batch_size: 1
  learning_rate: 0.0001
  num_workers: 5
  enable_val: False
  enable_dist: False