# YAML config for dataset, training, and model parameters

# Dataset parameters
dataset:
  n_flows_list: [1000]
  n_hosts_list: [3]
  shard: 0
  shard_list: [0,20000,20000] # [start, end, num]
  sample_list: [0,1,1] # [start, end, num]
  lr: 10
  train_frac: 0.9
  topo_type: "_topo-pl-x_"
  output_type: "fctSldn" # fctSldn, queueLen

# Model parameters
model:
  model_name: "lstm"
  n_layer: 2
  loss_fn_type: "l1"
  hidden_size: 64
  dropout: 0.0
  enable_bidirectional: True

# Training parameters
training:
  # gpu: [0,0,1,1,2,2,3,3]
  gpu: [0,1,2,3]
  n_epochs: 1000
  batch_size: 32
  learning_rate: 0.0001
  num_workers: 16
  enable_val: True
  enable_dist: True