# YAML config for dataset, training, and model parameters

# Dataset parameters
dataset:
  n_flows_list: [2000]
  n_hosts_list: [3,5,7]
  # n_hosts_list: [21]
  shard: 0
  shard_list: [0,2000,2000] # [start, end, num]
  sample_list: [0,1,1] # [start, end, num]
  lr: 10
  train_frac: 0.9
  topo_type: "_topo-pl-x_"
  output_type: "fctSldn" # fctSldn, queueLen
  enable_segmentation: True
  segments_per_seq: 40
  sampling_method: "balanced" # weighted, uniform, balanced
  enable_path: False

# Model parameters
model:
  model_name: "lstm"
  input_size: 3
  n_layer: 2
  gcn_n_layer: 2
  loss_fn_type: "l1"
  hidden_size: 512
  gcn_hidden_size: 3
  dropout: 0.0
  enable_bidirectional: True
  enable_positional_encoding: False
  enable_gcn: False

# Training parameters
training:
  # gpu: [0,0,1,1,2,2,3,3]
  gpu: [0,1,2,3]
  n_epochs: 1000
  batch_size: 32
  learning_rate: 0.0001
  num_workers: 8
  enable_val: True
  enable_dist: True