# YAML config for dataset, training, and model parameters

# Dataset parameters
dataset:
  n_flows_list: [2000]
  n_hosts_list: [32]
  shard: 0
  shard_list: [0,4000,4000] # [start, end, num]
  lr: 10
  train_frac: 0.9
  topo_type: "_topology_flows"
  enable_segmentation: True
  sampling_method: "balanced" # weighted, uniform, balanced
  enable_topo: True
  flow_size_threshold: 100000000
  enable_flowsim_gt: False
  enable_remainsize: True
  enable_queuelen: True

# Model parameters
model:
  model_name: "lstm"
  input_size: 2
  n_layer: 2
  gcn_n_layer: 3
  loss_fn_type: "l1"
  hidden_size: 200
  gcn_hidden_size: 300
  dropout: 0.2
  enable_positional_encoding: False
  enable_gnn: True
  enable_lstm: True
  enable_link_state: True

# Training parameters
training:
  gpu: [1]
  n_epochs: 15
  batch_size: 2
  learning_rate: 0.0001
  num_workers: 2
  enable_val: True
  enable_dist: False