# YAML config for dataset, training, and model parameters

# Dataset parameters
dataset:
  n_flows_list: [2000]
  n_hosts_list: [21]
  shard: 0
  shard_list: [0,500,500] # [start, end, num]
  sample_list: [0,1,1] # [start, end, num]
  lr: 10
  train_frac: 0.9
  topo_type: "_topo-pl-x_"
  output_type: "fctSldn" # fctSldn, queueLen
  enable_segmentation: True
  segments_per_seq: 100
  sampling_method: "balanced" # uniform, weighted, balanced

# Model parameters
model:
  model_name: "lstm"
  n_layer: 2
  loss_fn_type: "l1"
  hidden_size: 64
  dropout: 0.0
  enable_bidirectional: True

# Training parameters
training:
  gpu: [3]
  n_epochs: 4
  batch_size: 2
  learning_rate: 0.001
  num_workers: 1
  enable_val: True
  enable_dist: False